### ISSUE TITLE
License

### ISSUE THREAD

**Issue by test2a** [geongeorge/GST-HSN-Codes-Fetch#1]
Hi.

Can you add a license to your repo? Id like to use it but unless its agpl or likes, I cant use it. I would have to look elsewhere otherwise.
Thanks

**Comment by geongeorge** [comment]
Hey @test2a 
Let's make it MIT. If you want create a PR with the license file. I'll merge it right away

**Comment by test2a** [comment]
Oh. I am involved with something called gnukhata.

I like to suggest stuff for them to improve the software and your module came up in the search for HSN.
It uses GPL so I think mit would be alright although I would like to talk to devs there

**Comment by test2a** [comment]
From what I know about licenses, mit should would in GPL code so yeah, it should be fine

**Comment by geongeorge** [comment]
Solved by https://github.com/geongeorge/GST-HSN-Codes-Fetch/pull/2
